import Head from "next/head";

import Access from "./components/access";
import Apply from "./components/apply";
import Contact from "./components/contact";
import Footer from "./components/footer";
import Header from "./components/header";
import Hero from "./components/hero";
import Lead from "./components/lead";
import Products from "./components/products";
import Staff from "./components/staff";

// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Hero />
      <main>
        <Lead />
        <Products />
        <Staff />
        <Apply />
        <Access />
        <Contact />
      </main>
      <Footer />
    </>
  );
}
